### ISSUE TITLE
To-do List 

### ISSUE THREAD

**Issue by bytelisa** [valejin/StudyPal#4]
Bacheca per la lista delle cose da fare

**Comment by valejin** [comment]
- [x] Font della stessa dimensione (pagina registrazione)
- [x] Controlli su registrazione (validita dell'email, e uguaglianza tra password e confermapassword)
- [x] Ombra checkbox sono tutor
- [x] Pulsanti stessa dimensione
- [x] Controllo punto e font conferma registrazione
- [x] Inserisci materia più grande
- [x] Slider arrotona
- [x] Giorni disponibili puoi fare pallini
- [x] Sistemare immagine home
- [x] Prezzo tariffa da mostrare quando ritorno su gestione profilo!
- [x] Potrebbe non servire descrizione prenotazioni attive
- [x] Pulsante indietro registrazione da uniformare
- [x] Tariffa max nei filtri invece che tariffa
- [x] Modalità non label!!!!
- [x] Ricarica i filtri (nella cercaRipetizione da parte dello studente)
- [x] Giorni disponibili da sistemare L MA ME ETC per risparmiare spazio
- [x] Pallino colorato invece che prenota prenoya prenota
- [x] Togliere nome cognome come sottocolonna di qualcos'altro
- [x] RICHIEDI INVECE CHE PRENOTA NELLA TABLE
- [x] Togli descrizione prenota ripetizione per guadagnare spazio
- [x] Richieste inviate gestione prenotazioni su due righe
- [x] Nome clickabile nella table dei risultati per accedere al profilo dei tutor
- [x] Tariffa massima nei filtri se non specificata è 50!!
- [x] Tariffa oraria con euro nella tabella dei risultati
- [x] Modalità selezionabile per forza (almeno una delle due) al momento della ricerca
- [x] Pulsante indietro alla stessa dimensione
- [x] ALLARGARE TUTTO
- [x] Stessa altezza titoli
- [x] Se vado in gestisci profilo mi viene mostrato il luogo che avevo scritto in passato ma se non lo modifico e confermo questo viene salvato come null
- [x] Richiesta rifiutata tutor scritta rosaa

**Comment by bytelisa** [comment]
NOTE:

- modalità label nei filtri della pagina "risultati ricerca" -> nel caso di sola ricerca per materia cerchiamo come In presenza e online (true true), ovvero in OR. Però questo avviene anche se l'utente non seleziona nessuna delle due! Da accordarsi sul significato della doppia selezione... è un AND o un OR?
- nome della materia che ci portiamo appresso nella prenotazione è sempre quello scritto dall'utente. Dato che cerchiamo con like e l'utente può scrivere male forse sarebbe meglio controllarlo e riportare quello scritto dal tutor che "teoricamente" dovrebbe essere scritto bene(?). Forse è una preoccupazione in più ma se avanza tempo si può fare

**Comment by bytelisa** [comment]
Dobbiamo modificare query per inserire nella tabella tutor anche nome e cognome presi al momento della registrazione!

**Comment by bytelisa** [comment]
Sistemare ricerca per giorni: se cerchiamo tutor e siamo interessati a disponibilità lunedì/venerdì, quelli che hanno la disponibilità lunedì, martedì non appaiono!!!!!!!!! Dobbiamo spezzare la stringa e controllare su tutti i giorni per avere i giorni in OR!!!!!!!

**Comment by bytelisa** [comment]
**Note importanti, verificate da appunti:**
- togliere tutte le query dai DAO e inserirle nella classe Query
- non specificato dappertutto!!!! in alcuni punti non stampa niente

**Comment by bytelisa** [comment]
- [ ] Notato che possiamo fare la ricerca con il filtro in presenza senza selezionare il luogo! Da sistemare.

**Comment by valejin** [comment]
**CODE SMELL DA SISTEMARE**

**controller.application.student**
- [x] HomeStudenteController è vuoto  (possiamo cancellare?)
- [x] PrenotaRipetizioneController ha un TODO
- [x] RisultatiRicercaController è vuoto (possiamo cancellare ?)

**controller.application.tutor**
- [x] VisualizzaRichiestaController è vuoto

**model**
- [x] PrenotazioneModel ha 11 parametri

**view.first.gui**
- [x] cercaRipetizioneGui -> 1 code smell in initialize
- [x] RisultatiRicercaGuiController -> 1 code smell in initialize
- [x] PopupGui è vuoto   (lalto studente)

**view.second.gui**
- [x] VisualizzaRichiesteStudenteCLI c'è un TODO
- [x] GestisciProfiloCLI -> 6 code smell
- [x] VisualizzaRichiestaCLI -> 2 code smell
- [x] RichiesteTutorCLI -> 3 code smell

- [x] in HomeTutorCLI e HomeStudentCLI
